//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStoreClientSoap.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Games", Namespace="http://schemas.datacontract.org/2004/07/GameStorelibrary")]
    [System.SerializableAttribute()]
    public partial class Games : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AntalPåLagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AntalPåLager {
            get {
                return this.AntalPåLagerField;
            }
            set {
                if ((this.AntalPåLagerField.Equals(value) != true)) {
                    this.AntalPåLagerField = value;
                    this.RaisePropertyChanged("AntalPåLager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGames", ReplyAction="http://tempuri.org/IService1/GetAllGamesResponse")]
        GameStoreClientSoap.ServiceReference1.Games[] GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllGames", ReplyAction="http://tempuri.org/IService1/GetAllGamesResponse")]
        System.Threading.Tasks.Task<GameStoreClientSoap.ServiceReference1.Games[]> GetAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneGame", ReplyAction="http://tempuri.org/IService1/GetOneGameResponse")]
        GameStoreClientSoap.ServiceReference1.Games GetOneGame(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOneGame", ReplyAction="http://tempuri.org/IService1/GetOneGameResponse")]
        System.Threading.Tasks.Task<GameStoreClientSoap.ServiceReference1.Games> GetOneGameAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        void DeleteGame(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        System.Threading.Tasks.Task DeleteGameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGame", ReplyAction="http://tempuri.org/IService1/UpdateGameResponse")]
        void UpdateGame(int id, string title, int AntalPåLager, double Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGame", ReplyAction="http://tempuri.org/IService1/UpdateGameResponse")]
        System.Threading.Tasks.Task UpdateGameAsync(int id, string title, int AntalPåLager, double Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGame", ReplyAction="http://tempuri.org/IService1/AddGameResponse")]
        void AddGame(int id, string title, double price, int antalPåLager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGame", ReplyAction="http://tempuri.org/IService1/AddGameResponse")]
        System.Threading.Tasks.Task AddGameAsync(int id, string title, double price, int antalPåLager);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GameStoreClientSoap.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GameStoreClientSoap.ServiceReference1.IService1>, GameStoreClientSoap.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStoreClientSoap.ServiceReference1.Games[] GetAllGames() {
            return base.Channel.GetAllGames();
        }
        
        public System.Threading.Tasks.Task<GameStoreClientSoap.ServiceReference1.Games[]> GetAllGamesAsync() {
            return base.Channel.GetAllGamesAsync();
        }
        
        public GameStoreClientSoap.ServiceReference1.Games GetOneGame(string id) {
            return base.Channel.GetOneGame(id);
        }
        
        public System.Threading.Tasks.Task<GameStoreClientSoap.ServiceReference1.Games> GetOneGameAsync(string id) {
            return base.Channel.GetOneGameAsync(id);
        }
        
        public void DeleteGame(int id) {
            base.Channel.DeleteGame(id);
        }
        
        public System.Threading.Tasks.Task DeleteGameAsync(int id) {
            return base.Channel.DeleteGameAsync(id);
        }
        
        public void UpdateGame(int id, string title, int AntalPåLager, double Price) {
            base.Channel.UpdateGame(id, title, AntalPåLager, Price);
        }
        
        public System.Threading.Tasks.Task UpdateGameAsync(int id, string title, int AntalPåLager, double Price) {
            return base.Channel.UpdateGameAsync(id, title, AntalPåLager, Price);
        }
        
        public void AddGame(int id, string title, double price, int antalPåLager) {
            base.Channel.AddGame(id, title, price, antalPåLager);
        }
        
        public System.Threading.Tasks.Task AddGameAsync(int id, string title, double price, int antalPåLager) {
            return base.Channel.AddGameAsync(id, title, price, antalPåLager);
        }
    }
}
